version: '3.8'


services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: twitch
      MYSQL_ROOT_PASSWORD: secret
      TZ: UTC
    volumes:
      - mysql-local:/var/lib/mysql
    ports:
      - 3306:3306


# permanent storage of data.
volumes:
  mysql-local:

datasource:
  url: jdbc:mysql://${DATABASE_URL:localhost}:3306/twitch?createDatabaseIfNotExist=true
  username: ${DATABASE_USERNAME:root}
  password: ${DATABASE_PASSWORD:secret}
  driver-class-name: com.mysql.cj.jdbc.Driver